# Generated by Django 5.2 on 2025-04-11 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('been_liked', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Recepie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('text', models.TextField()),
                ('main_recepie', models.TextField()),
                ('time', models.TimeField()),
                ('likes', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('img', models.ImageField(upload_to='')),
                ('slug', models.SlugField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recepie.account')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepie.categorie')),
                ('likers', models.ManyToManyField(related_name='likes', to='recepie.account')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('measurement', models.CharField(max_length=20)),
                ('number', models.IntegerField()),
                ('recepie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recepie.recepie')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recepie.account')),
                ('recepie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recepie.recepie')),
            ],
        ),
    ]
