# Generated by Django 5.2 on 2025-04-11 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recepie',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='recepie',
            name='likers',
            field=models.ManyToManyField(null=True, related_name='likes', to='recepie.account'),
        ),
        migrations.AlterField(
            model_name='recepie',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
