# Generated by Django 5.2 on 2025-04-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepie', '0002_alter_recepie_date_alter_recepie_likers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recepie',
            name='likers',
            field=models.ManyToManyField(related_name='likes', to='recepie.account'),
        ),
        migrations.AlterField(
            model_name='recepie',
            name='name',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
